const _SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN || '';
const _SLACK_SIGNING_SECRET = process.env.SLACK_SIGNING_SECRET || '';
const _SLACK_API_URL = process.env.SLACK_API_URL || '';
const _SLACK_USER_ID_ERROR_CONTACT = process.env.SLACK_USER_ID_ERROR_CONTACT || '';

const _BAMBOOHR_API_KEY = process.env.BAMBOOHR_API_KEY || '';
const _BAMBOOHR_SUBDOMAIN = process.env.BAMBOOHR_SUBDOMAIN || '';
const _BAMBOOHR_API_URL = process.env.BAMBOOHR_API_URL || '';

const _PORT = process.env.PORT || '';

const environment = {
  SLACK_BOT_TOKEN: _SLACK_BOT_TOKEN,
  SLACK_SIGNING_SECRET: _SLACK_SIGNING_SECRET,
  SLACK_API_URL: _SLACK_API_URL,
  SLACK_USER_ID_ERROR_CONTACT: _SLACK_USER_ID_ERROR_CONTACT,

  BAMBOOHR_API_KEY: _BAMBOOHR_API_KEY,
  BAMBOOHR_SUBDOMAIN: _BAMBOOHR_SUBDOMAIN,
  BAMBOOHR_API_URL: _BAMBOOHR_API_URL,

  PORT: _PORT,
};

module.exports = environment;
